add_crusta_exe(construo
    src/construo/Builder.h
    src/construo/Builder.hpp
    src/construo/construoGlobals.h
    src/construo/ConstruoSettings.h
    src/construo/ConstruoVisualizer.h
    src/construo/Converters.h
    src/construo/GdalImageFile.h
    src/construo/GdalImageFile.hpp
    src/construo/GdalTransform.h
    src/construo/GeometryTypes.h
    src/construo/GeoTransform.h
    src/construo/ImageCoverage.h
    src/construo/ImageFile.h
    src/construo/ImageFile.hpp
    src/construo/ImageFileLoader.h
    src/construo/ImageFileLoader.hpp
    src/construo/ImagePatch.h
    src/construo/ImagePatch.hpp
    src/construo/ImageTransform.h
    src/construo/SphereCoverage.h
    src/construo/SubsampleFilter.h
    src/construo/SubsampleFilter.hpp
    src/construo/TpmFile.h
    src/construo/TpmImageFile.h
    src/construo/TpmImageFile.hpp
    src/construo/Tree.h
    src/construo/Tree.hpp

    src/construo/Construo.cpp
    src/construo/construoGlobals.cpp
    src/construo/ConstruoSettings.cpp
    src/construo/ConstruoVisualizer.cpp
    src/construo/GdalImageFile.cpp
    src/construo/GdalTransform.cpp
    src/construo/GeoTransform.cpp
    src/construo/ImageCoverage.cpp
    src/construo/ImageTransform.cpp
    src/construo/SphereCoverage.cpp
    src/construo/TpmFile.cpp
    src/construo/Tree.cpp
)
