set(CRUSTACORE_SOURCES
    src/crusta/GL/GlProgram.h
    src/crusta/GL/VruiGlew.h
    src/crusta/GLMotif/ColorHexagon.h
    src/crusta/GLMotif/ColorMapEditor.h
    src/crusta/GLMotif/ColorMapInOut.h
    src/crusta/GLMotif/ColorPicker.h
    src/crusta/GLMotif/ColorPickerWindow.h
    src/crusta/GLMotif/PaletteEditor.h
    src/crusta/GLMotif/RangeEditor.h
    src/crusta/GLMotif/RelativeSlider.h
    src/crusta/Misc/ColorMap.h

    src/crusta/basics.h
    src/crusta/Cache.h
    src/crusta/Cache.hpp
    src/crusta/checkGl.h
    src/crusta/CrustaComponent.h
    src/crusta/CrustaSettings.h
    src/crusta/CrustaVisualizer.h
    src/crusta/DataIndex.h
    src/crusta/DemHeight.h
    src/crusta/DemHeightGlobeData.h
    src/crusta/GlobeData.h
    src/crusta/GlobeFile.h
    src/crusta/GlobeFile.hpp
    src/crusta/Homography.h
    src/crusta/IdGenerator.h
    src/crusta/LayerData.h
    src/crusta/LayerDataGlobeData.h
    src/crusta/PixelOps.h
    src/crusta/PixelOps.hpp
    src/crusta/Polyhedron.h
    src/crusta/PolyhedronLoader.h
    src/crusta/QuadtreeFile.h
    src/crusta/QuadtreeFile.hpp
    src/crusta/Refinement.h
    src/crusta/Refinement.hpp
    src/crusta/ResourceLocator.h
    src/crusta/Scope.h
    src/crusta/Scope.hpp
    src/crusta/Section.h
    src/crusta/Sphere.h
    src/crusta/SurfacePoint.h
    src/crusta/SurfaceProbeTool.h
    src/crusta/SurfaceProjector.h
    src/crusta/SurfaceTool.h
    src/crusta/TextureColor.h
    src/crusta/TextureColorGlobeData.h
    src/crusta/TileIndex.h
    src/crusta/Timer.h
    src/crusta/Tool.h
    src/crusta/TreeIndex.h
    src/crusta/Triacontahedron.h
    src/crusta/Triangle.h
    src/crusta/Vector3ui8.h
    src/crusta/ViewLod.h
    src/crusta/VisibilityEvaluator.h
    src/crusta/Visualizer.h

    src/crusta/GL/GlProgram.cpp
    src/crusta/GL/VruiGlew.cpp
    src/crusta/GLMotif/ColorHexagon.cpp
    src/crusta/GLMotif/ColorMapEditor.cpp
    src/crusta/GLMotif/ColorMapInOut.cpp
    src/crusta/GLMotif/ColorPicker.cpp
    src/crusta/GLMotif/ColorPickerWindow.cpp
    src/crusta/GLMotif/PaletteEditor.cpp
    src/crusta/GLMotif/RangeEditor.cpp
    src/crusta/GLMotif/RelativeSlider.cpp
    src/crusta/Misc/ColorMap.cpp

    src/crusta/CrustaSettings.cpp
    src/crusta/CrustaVisualizer.cpp
    src/crusta/DataIndex.cpp
    src/crusta/Homography.cpp
    src/crusta/PolyhedronLoader.cpp
    src/crusta/ResourceLocator.cpp
    src/crusta/Scope.cpp
    src/crusta/Section.cpp
    src/crusta/Sphere.cpp
    src/crusta/Tool.cpp
    src/crusta/TreeIndex.cpp
    src/crusta/Triacontahedron.cpp
    src/crusta/Visualizer.cpp
)

add_library(crustacore STATIC ${CRUSTACORE_SOURCES})
